# Generated by Django 2.2.5 on 2019-09-13 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attndance', '0002_emplyees_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='emplyees',
            new_name='employees',
        ),
    ]
